### ISSUE TITLE
window 咋安装使用

### ISSUE THREAD

**Issue by qidouhai** [Mistsink/yzh-music-back#1]

**Comment by Mistsink** [comment]
这是基于go的，就按照go的一般项目运行就好了

**Comment by qidouhai** [comment]
我不会go 哦 能打包下吗

**Comment by Mistsink** [comment]
我的评价是寄，就去go官网下载下，然后cmd里面cd到这个项目目录下，然后看下这个吧https://blog.csdn.net/baidu_34122324/article/details/90183394

**Comment by Mistsink** [comment]
今天更新了嗷，非常建议使用docker运行哈。
1. 安装docker
2. 下载项目中的 docker-compose.yml（只需要这个文件）
3. 在 cmd 进入 yml 文件所在目录
4. 运行 "docker compose up -d" 即可

打包的话比较麻烦，如果在上述操作中你不熟悉 docker 的话，可以 qq 联系我：3311737005
